services:
  postgres:
    image: postgres:latest
    container_name: aji
    environment:
      POSTGRES_USER: aji
      POSTGRES_PASSWORD: aji
      POSTGRES_DB: computer_shop
      PGDATA: /tmp/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/tmp/postgresql/data
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - ./initstructure:/initstructure
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs