version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: aji
    environment:
      POSTGRES_USER: aji
      POSTGRES_PASSWORD: aji
      POSTGRES_DB: computer_shop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
